### ISSUE TITLE
Heroku desteği

### ISSUE THREAD

**Issue by haliliceylan** [gHuseyinabi/RedditLinker#2]
Repoya buildpack desteği eklemek istiyorum bu şekilde, kolay bir şekilde sunuculara container olarak deploy edilebilir eğer bu fikire olumlu bakıyorsanız PR açmak isterim.

https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-python

**Comment by gHuseyinabi** [comment]
Geç baktığım için özür dilerim.
Herokuyu açmıştım ama pek de bilmiyorum. Gösterdiğiniz sitedekileri yapmıştım.
![logs](https://user-images.githubusercontent.com/68753989/112102766-ced1d200-8bb9-11eb-8308-2eb8694a1637.PNG)

**Comment by haliliceylan** [comment]
Tamam o zaman, şuan için ekstra bir configürasyona gerek yok.
